services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - ./:/app
      - ./Caddyfile.dev:/etc/frankenphp/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      SERVER_ROOT: /app/examples/public
    env_file:
      - .env
    tty: true
    depends_on:
      - redis
    ports:
      - "80:80" # HTTP

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    env_file:
      - .env
    depends_on:
      - redis
    command: php examples/bin/console app:worker

  redis:
    image: redis:8.4.0
    ports:
      - "6379:6379"

  e2e:
    build:
      context: e2e
      dockerfile: Dockerfile
    working_dir: /app/e2e
    volumes:
      - ./e2e:/app/e2e
    environment:
      BASE_URL: http://php
    env_file:
      - .env
    depends_on:
      - worker
      - redis
    command: >
      sh -c "npm install && npx playwright test"

volumes:
  caddy_data:
  caddy_config:
